version: '3.9'

services:
  node-server:
    container_name: my-node-app
    build: .
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   
      MYSQL_DATABASE: docker101 
    ports:
      - "3307:3306"
    volumes:
      - mysql_db_test:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db 
      PMA_USER: root  
      PMA_PASSWORD: root 
    ports:
      - "8888:80"
    depends_on:
      - db

volumes:
  mysql_db_test: